data_dir: !!python/object/apply:pathlib.PosixPath
- /
- root
- datasets2
- mle-bench-lite
- raw
- aerial-cactus-identification
- prepared
- public
desc_file: !!python/object/apply:pathlib.PosixPath
- /
- root
- yrwang
- aideml
- dataset
- full_instructions
- aerial-cactus-identification
- full_instructions.txt
goal: null
eval: null
log_dir: !!python/object/apply:pathlib.PosixPath
- /
- root
- yrwang
- aideml
- logs
- 20steps
- aerial-cactus-identification
log_level: INFO
workspace_dir: !!python/object/apply:pathlib.PosixPath
- /
- root
- yrwang
- aideml
- workspaces
- aerial-cactus-identification
preprocess_data: true
copy_data: true
exp_name: aerial-cactus-identification
exec:
  timeout: 3600
  agent_file_name: runfile.py
  format_tb_ipython: false
agent:
  steps: 20
  time_limit: 86400
  k_fold_validation: 5
  expose_prediction: false
  data_preview: true
  convert_system_to_user: false
  obfuscate: false
  code:
    model: gpt-4o-2024-08-06
    temp: 0.5
  feedback:
    model: gpt-4o-2024-08-06
    temp: 0.5
  search:
    max_debug_depth: 3
    debug_prob: 0.5
    num_drafts: 5
